config/routes.rb
Mythesis2::Application.routes.draw do
  resources :test_article_attribute_sentences

  resources :attribute_values

  resources :attributes

  resources :infobox_templates

  resources :articles do
    collection do
      get :import
      get :create_raw_attribute_value
      get :create_senteces_file
      get :write_article_to_files
      get :find_sentences_with_value
      get :create_doccat_training_file
      get :train_doccat
      get :create_vector_space_for_attribute
      get :create_train_for_filter_by_cluster
      get :create_training_data_for_CRF
      get :training_CRF
      get :doccat_test_files
      get :filter
      get :create_test_files_crf
      get :test_CRF
      get :get_result
      get :run_all
    end
  end

end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
  validates :name, presence: true
  
  belongs_to :infobox_template
  
  has_many :attribute_values
  has_many :attribute_sentences
  has_many :test_article_attribute_sentences
end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
  before_action :set_attribute, only: [:show, :edit, :update, :destroy]

  # GET /attributes
  # GET /attributes.json
  def index
    @attributes = Attribute.all
  end

  # GET /attributes/1
  # GET /attributes/1.json
  def show
  end

  # GET /attributes/new
  def new
    @attribute = Attribute.new
  end

  # GET /attributes/1/edit
  def edit
  end

  # POST /attributes
  # POST /attributes.json
  def create
    @attribute = Attribute.new(attribute_params)

    respond_to do |format|
      if @attribute.save
        format.html { redirect_to @attribute, notice: 'Attribute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attribute }
      else
        format.html { render action: 'new' }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attributes/1
  # PATCH/PUT /attributes/1.json
  def update
    respond_to do |format|
      if @attribute.update(attribute_params)
        format.html { redirect_to @attribute, notice: 'Attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attributes/1
  # DELETE /attributes/1.json
  def destroy
    @attribute.destroy
    respond_to do |format|
      format.html { redirect_to attributes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attribute
      @attribute = Attribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attribute_params
      params.require(:attribute).permit(:name, :infobox_template_id)
    end
end

app/helpers/attributes_helper.rb
module AttributesHelper
end

app/views/attributes/_form.html.erb
<%= form_for(@attribute) do |f| %>
  <% if @attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>

      <ul>
      <% @attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :infobox_template_id %><br>
    <%= f.number_field :infobox_template_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attributes/edit.html.erb
<h1>Editing attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @attribute %> |
<%= link_to 'Back', attributes_path %>

app/views/attributes/index.html.erb
<h1>Listing attributes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Infobox template</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attributes.each do |attribute| %>
      <tr>
        <td><%= attribute.name %></td>
        <td><%= attribute.infobox_template_id %></td>
        <td><%= link_to 'Show', attribute %></td>
        <td><%= link_to 'Edit', edit_attribute_path(attribute) %></td>
        <td><%= link_to 'Destroy', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attribute', new_attribute_path %>

app/views/attributes/new.html.erb
<h1>New attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', attributes_path %>

app/views/attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attribute.name %>
</p>

<p>
  <strong>Infobox template:</strong>
  <%= @attribute.infobox_template_id %>
</p>

<%= link_to 'Edit', edit_attribute_path(@attribute) %> |
<%= link_to 'Back', attributes_path %>