config/routes.rb
Mythesis2::Application.routes.draw do
  resources :test_article_attribute_sentences

  resources :attribute_values

  resources :attributes

  resources :infobox_templates

  resources :articles do
    collection do
      get :import
      get :create_raw_attribute_value
      get :create_senteces_file
      get :write_article_to_files
      get :find_sentences_with_value
      get :create_doccat_training_file
      get :train_doccat
      get :create_vector_space_for_attribute
      get :create_train_for_filter_by_cluster
      get :create_training_data_for_CRF
      get :training_CRF
      get :doccat_test_files
      get :filter
      get :create_test_files_crf
      get :test_CRF
      get :get_result
      get :run_all
    end
  end

end

app/models/infobox_template.rb
class InfoboxTemplate < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  
  has_many :attributes
  has_many :articles
end

app/controllers/infobox_templates_controller.rb
class InfoboxTemplatesController < ApplicationController
  before_action :set_infobox_template, only: [:show, :edit, :update, :destroy]

  # GET /infobox_templates
  # GET /infobox_templates.json
  def index
    @infobox_templates = InfoboxTemplate.all
  end

  # GET /infobox_templates/1
  # GET /infobox_templates/1.json
  def show
  end

  # GET /infobox_templates/new
  def new
    @infobox_template = InfoboxTemplate.new
  end

  # GET /infobox_templates/1/edit
  def edit
  end

  # POST /infobox_templates
  # POST /infobox_templates.json
  def create
    @infobox_template = InfoboxTemplate.new(infobox_template_params)

    respond_to do |format|
      if @infobox_template.save
        format.html { redirect_to @infobox_template, notice: 'Infobox template was successfully created.' }
        format.json { render action: 'show', status: :created, location: @infobox_template }
      else
        format.html { render action: 'new' }
        format.json { render json: @infobox_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infobox_templates/1
  # PATCH/PUT /infobox_templates/1.json
  def update
    respond_to do |format|
      if @infobox_template.update(infobox_template_params)
        format.html { redirect_to @infobox_template, notice: 'Infobox template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @infobox_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infobox_templates/1
  # DELETE /infobox_templates/1.json
  def destroy
    @infobox_template.destroy
    respond_to do |format|
      format.html { redirect_to infobox_templates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_infobox_template
      @infobox_template = InfoboxTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def infobox_template_params
      params.require(:infobox_template).permit(:name)
    end
end

app/helpers/infobox_templates_helper.rb
module InfoboxTemplatesHelper
end

app/views/infobox_templates/_form.html.erb
<%= form_for(@infobox_template) do |f| %>
  <% if @infobox_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@infobox_template.errors.count, "error") %> prohibited this infobox_template from being saved:</h2>

      <ul>
      <% @infobox_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infobox_templates/edit.html.erb
<h1>Editing infobox_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @infobox_template %> |
<%= link_to 'Back', infobox_templates_path %>

app/views/infobox_templates/index.html.erb
<h1>Listing infobox_templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @infobox_templates.each do |infobox_template| %>
      <tr>
        <td><%= infobox_template.name %></td>
        <td><%= link_to 'Show', infobox_template %></td>
        <td><%= link_to 'Edit', edit_infobox_template_path(infobox_template) %></td>
        <td><%= link_to 'Destroy', infobox_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Infobox template', new_infobox_template_path %>

app/views/infobox_templates/new.html.erb
<h1>New infobox_template</h1>

<%= render 'form' %>

<%= link_to 'Back', infobox_templates_path %>

app/views/infobox_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @infobox_template.name %>
</p>

<%= link_to 'Edit', edit_infobox_template_path(@infobox_template) %> |
<%= link_to 'Back', infobox_templates_path %>