config/routes.rb
Mythesis2::Application.routes.draw do
  resources :test_article_attribute_sentences

  resources :attribute_values

  resources :attributes

  resources :infobox_templates

  resources :articles do
    collection do
      get :import
      get :create_raw_attribute_value
      get :create_senteces_file
      get :write_article_to_files
      get :find_sentences_with_value
      get :create_doccat_training_file
      get :train_doccat
      get :create_vector_space_for_attribute
      get :create_train_for_filter_by_cluster
      get :create_training_data_for_CRF
      get :training_CRF
      get :doccat_test_files
      get :filter
      get :create_test_files_crf
      get :test_CRF
      get :get_result
      get :run_all
    end
  end

end

app/models/attribute_value.rb
class AttributeValue < ActiveRecord::Base
  belongs_to :article
  belongs_to :attribute
end

app/controllers/attribute_values_controller.rb
class AttributeValuesController < ApplicationController
  before_action :set_attribute_value, only: [:show, :edit, :update, :destroy]

  # GET /attribute_values
  # GET /attribute_values.json
  def index
    @attribute_values = AttributeValue.all
  end

  # GET /attribute_values/1
  # GET /attribute_values/1.json
  def show
  end

  # GET /attribute_values/new
  def new
    @attribute_value = AttributeValue.new
  end

  # GET /attribute_values/1/edit
  def edit
  end

  # POST /attribute_values
  # POST /attribute_values.json
  def create
    @attribute_value = AttributeValue.new(attribute_value_params)

    respond_to do |format|
      if @attribute_value.save
        format.html { redirect_to @attribute_value, notice: 'Attribute value was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attribute_value }
      else
        format.html { render action: 'new' }
        format.json { render json: @attribute_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attribute_values/1
  # PATCH/PUT /attribute_values/1.json
  def update
    respond_to do |format|
      if @attribute_value.update(attribute_value_params)
        format.html { redirect_to @attribute_value, notice: 'Attribute value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attribute_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attribute_values/1
  # DELETE /attribute_values/1.json
  def destroy
    @attribute_value.destroy
    respond_to do |format|
      format.html { redirect_to attribute_values_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attribute_value
      @attribute_value = AttributeValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attribute_value_params
      params.require(:attribute_value).permit(:article_id, :attribute_id, :value)
    end
end

app/helpers/attribute_values_helper.rb
module AttributeValuesHelper
end

app/views/attribute_values/_form.html.erb
<%= form_for(@attribute_value) do |f| %>
  <% if @attribute_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute_value.errors.count, "error") %> prohibited this attribute_value from being saved:</h2>

      <ul>
      <% @attribute_value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :attribute_id %><br>
    <%= f.number_field :attribute_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attribute_values/edit.html.erb
<h1>Editing attribute_value</h1>

<%= render 'form' %>

<%= link_to 'Show', @attribute_value %> |
<%= link_to 'Back', attribute_values_path %>

app/views/attribute_values/index.html.erb
<h1>Listing attribute_values</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Attribute</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attribute_values.each do |attribute_value| %>
      <tr>
        <td><%= attribute_value.article_id %></td>
        <td><%= attribute_value.attribute_id %></td>
        <td><%= attribute_value.value %></td>
        <td><%= link_to 'Show', attribute_value %></td>
        <td><%= link_to 'Edit', edit_attribute_value_path(attribute_value) %></td>
        <td><%= link_to 'Destroy', attribute_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attribute value', new_attribute_value_path %>

app/views/attribute_values/new.html.erb
<h1>New attribute_value</h1>

<%= render 'form' %>

<%= link_to 'Back', attribute_values_path %>

app/views/attribute_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @attribute_value.article_id %>
</p>

<p>
  <strong>Attribute:</strong>
  <%= @attribute_value.attribute_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @attribute_value.value %>
</p>

<%= link_to 'Edit', edit_attribute_value_path(@attribute_value) %> |
<%= link_to 'Back', attribute_values_path %>