config/routes.rb
Mythesis2::Application.routes.draw do
  resources :test_article_attribute_sentences

  resources :attribute_values

  resources :attributes

  resources :infobox_templates

  resources :articles do
    collection do
      get :import
      get :create_raw_attribute_value
      get :create_senteces_file
      get :write_article_to_files
      get :find_sentences_with_value
      get :create_doccat_training_file
      get :train_doccat
      get :create_vector_space_for_attribute
      get :create_train_for_filter_by_cluster
      get :create_training_data_for_CRF
      get :training_CRF
      get :doccat_test_files
      get :filter
      get :create_test_files_crf
      get :test_CRF
      get :get_result
      get :run_all
    end
  end

end

app/models/test_article_attribute_sentence.rb
class TestArticleAttributeSentence < ActiveRecord::Base
  
  belongs_to :article
  belongs_to :attribute
end

app/controllers/test_article_attribute_sentences_controller.rb
class TestArticleAttributeSentencesController < ApplicationController
  before_action :set_test_article_attribute_sentence, only: [:show, :edit, :update, :destroy]

  # GET /test_article_attribute_sentences
  # GET /test_article_attribute_sentences.json
  def index
    @test_article_attribute_sentences = TestArticleAttributeSentence.all
  end

  # GET /test_article_attribute_sentences/1
  # GET /test_article_attribute_sentences/1.json
  def show
  end

  # GET /test_article_attribute_sentences/new
  def new
    @test_article_attribute_sentence = TestArticleAttributeSentence.new
  end

  # GET /test_article_attribute_sentences/1/edit
  def edit
  end

  # POST /test_article_attribute_sentences
  # POST /test_article_attribute_sentences.json
  def create
    @test_article_attribute_sentence = TestArticleAttributeSentence.new(test_article_attribute_sentence_params)

    respond_to do |format|
      if @test_article_attribute_sentence.save
        format.html { redirect_to @test_article_attribute_sentence, notice: 'Test article attribute sentence was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test_article_attribute_sentence }
      else
        format.html { render action: 'new' }
        format.json { render json: @test_article_attribute_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_article_attribute_sentences/1
  # PATCH/PUT /test_article_attribute_sentences/1.json
  def update
    respond_to do |format|
      if @test_article_attribute_sentence.update(test_article_attribute_sentence_params)
        format.html { redirect_to @test_article_attribute_sentence, notice: 'Test article attribute sentence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test_article_attribute_sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_article_attribute_sentences/1
  # DELETE /test_article_attribute_sentences/1.json
  def destroy
    @test_article_attribute_sentence.destroy
    respond_to do |format|
      format.html { redirect_to test_article_attribute_sentences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_article_attribute_sentence
      @test_article_attribute_sentence = TestArticleAttributeSentence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_article_attribute_sentence_params
      params.require(:test_article_attribute_sentence).permit(:article_id, :attribute_id, :sentence)
    end
end

app/helpers/test_article_attribute_sentences_helper.rb
module TestArticleAttributeSentencesHelper
end

app/views/test_article_attribute_sentences/_form.html.erb
<%= form_for(@test_article_attribute_sentence) do |f| %>
  <% if @test_article_attribute_sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_article_attribute_sentence.errors.count, "error") %> prohibited this test_article_attribute_sentence from being saved:</h2>

      <ul>
      <% @test_article_attribute_sentence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :attribute_id %><br>
    <%= f.number_field :attribute_id %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_area :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_article_attribute_sentences/edit.html.erb
<h1>Editing test_article_attribute_sentence</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_article_attribute_sentence %> |
<%= link_to 'Back', test_article_attribute_sentences_path %>

app/views/test_article_attribute_sentences/index.html.erb
<h1>Listing test_article_attribute_sentences</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Attribute</th>
      <th>Sentence</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @test_article_attribute_sentences.each do |test_article_attribute_sentence| %>
      <tr>
        <td><%= test_article_attribute_sentence.article_id %></td>
        <td><%= test_article_attribute_sentence.attribute_id %></td>
        <td><%= test_article_attribute_sentence.sentence %></td>
        <td><%= link_to 'Show', test_article_attribute_sentence %></td>
        <td><%= link_to 'Edit', edit_test_article_attribute_sentence_path(test_article_attribute_sentence) %></td>
        <td><%= link_to 'Destroy', test_article_attribute_sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test article attribute sentence', new_test_article_attribute_sentence_path %>

app/views/test_article_attribute_sentences/new.html.erb
<h1>New test_article_attribute_sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', test_article_attribute_sentences_path %>

app/views/test_article_attribute_sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @test_article_attribute_sentence.article_id %>
</p>

<p>
  <strong>Attribute:</strong>
  <%= @test_article_attribute_sentence.attribute_id %>
</p>

<p>
  <strong>Sentence:</strong>
  <%= @test_article_attribute_sentence.sentence %>
</p>

<%= link_to 'Edit', edit_test_article_attribute_sentence_path(@test_article_attribute_sentence) %> |
<%= link_to 'Back', test_article_attribute_sentences_path %>